base_info:
  robot_type:                      4         # 0 球球 1 摩托 2 两轮箱子  3 四轮两驱 4  四轮四驱  
  scene:                           0
scene_config:
  - scene_type: 0
    scene_str:                     "sty"
    init_x:                        -10
    init_y:                        174
    init_z:                        0
    init_yaw:                      -1.57
  - scene_type: 1
    scene_str:                     "hwxc"
    init_x:                        -10
    init_y:                        174
    init_z:                        0
    init_yaw:                      0
  - scene_type: 2
    scene_str:                     "mgc"
    init_x:                        -10
    init_y:                        174
    init_z:                        0
    init_yaw:                      0
type_config:
    max_vx:                        3.5
    max_vz:                        1.0
    #cti_cmd_vel_smoother
    feedback_flag:                 0
    acc_x_up:                      0.4
    acc_x_down:                    2
    acc_z:                         0.5
    #move_controlloer
    distance_phase_goal:           3.0        
    acc_for_curva:                 0.28
    acc_for_x:                     0.2
    #waypoints_follow
    dis_for_back_global:           5          
    K_stop_enable:                 1
    dis_tolerate_for_end:          0.4
    dis_tolerate_for_course:       1.5
    rad_tolerate:                  6.25
    cos_proportion:                1.5
    rad_to_vz_proportion:          0.25
    reverse_vx:                    0.5
    #box
    guiderail2bumper:              0.05
    disLoadToUnload:               1.0
    disToLoad:                     1.0
